### ISSUE TITLE
i686-pc-windows-msvc support

### ISSUE THREAD

**Issue by sstadick** [adamkewley/libdeflater#13] opened 2021-09-10 16:45 UTC
Hi!

Before I go too far down the rabbit hole on [this issue](https://github.com/sstadick/gzp/issues/18) I wanted to check and see if this has come across your radar before. 

Looking at the docs here https://github.com/ebiggers/libdeflate, the build process for libdeflate on windows gets a bit complex. 

If you haven't hit this before, are you open to PRs to try to fix it and probably move libdeflater to github actions instead of travis?

**Comment by adamkewley** [comment] 2021-09-13 07:21
@sstadick I haven't encountered this before, no, :( - and I would be open to a fix.

I'm not so sure what the issue is, because `libdeflate-sys` doesn't seem to have any arch-specific compilation options in it (this might be the problem, also, though).

As for moving to GitHub actions, feel free. I imagine it will be a fairly straightforward port because `libdeflater` is a fairly low-dependency Rust+C build.

**Comment by sstadick** [comment] 2021-09-14 15:35
Thanks for the speedy reply! 

I also suspect that lack of options in `libdeflate-sys` are related to the problem. i686 support is not super high on my todo list at the moment, but I will eventually try to work back through this. Feel free to close this issue in the interim though!

**Comment by adamkewley** [comment] 2022-03-12 10:33
Closing this for now - I'm guessing i686 support isn't a big deal and the GitHub Action thing can be separately issued/PRed when the need for CI becomes handy (it always is, it's just that this particular library isn't big enough to worry about it *too* much)

**Closed by adamkewley** 2022-03-12 10:33 UTC
